name: Bug Report
description: File a bug report
labels: ['Bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By submitting this issue, 
        you agree to follow our [Code of Conduct](https://nebula-labs.atlassian.net/wiki/x/vAA-DQ)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Give a description of what the bug is
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Describe how to reproduce this bug. You can include include screenshots or logs if they would help!
        If putting logs, be sure to wrap with ```` ```bash ```` before your logs and ```` ``` ```` after 
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Describe the bug in more detail. You can include related issues, helpful 
        background knowledge, related documentation, or anything else that will help
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Where did you encounter the bug? You can include OS, browser, branch (clubs.utdnebula.com,
        dev.clubs.utdnebula.com, or a local development branch), or anything else to help us reproduce the bug
    validations:
      required: true
