name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'status: declined'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Thank you for your contribution! However, we won't be merging this PR for at least one of these reasons:
            - The issue this PR resolves is reserved for new recruits. You should instead find issues to work on using [these search filters](${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}/issues?q=is%3Aissue%20state%3Aopen%20-label%3A%22Recommended%20for%20Recruits%22).
            - This PR uses AI excessively. Please see Nebula Lab's [AI Policy](https://nebula-labs.atlassian.net/wiki/x/AgCwQw).
            - We plan to approach this issue in another way.
